### ISSUE TITLE
Cannot compile a component created with Docker named "component-name"

### ISSUE THREAD

**Issue by akosma** [projectsyn/commodore#152] opened 2020-07-28 11:09 UTC
When creating a component using the `docker run commodore:v0.2.0 component new component-name` command, the compilation does not work.

## Steps to Reproduce the Problem

Follow the steps below:

  1. `mkdir -p catalog inventory dependencies compiled`
  2. `docker run -i --rm --network=host --env-file=./.env --user="$(id -u)" --volume $PWD/catalog/:/app/catalog/ --volume $PWD/dependencies/:/app/dependencies/ --volume $PWD/inventory/:/app/inventory/ --volume ~/.ssh:/app/.ssh:ro --volume ~/.gitconfig:/app/.gitconfig:ro projectsyn/commodore:v0.2.0 catalog compile c-ancient-cherry-5082 --api-url=$LIEUTENANT_URL --api-token=$LIEUTENANT_TOKEN`
  3. `docker run -i --rm --user="$(id -u)" --volume ~/.ssh:/app/.ssh:ro --volume $PWD/catalog/:/app/catalog/ --volume $PWD/dependencies/:/app/dependencies/ --volume $PWD/inventory/:/app/inventory/ --volume ~/.gitconfig:/app/.gitconfig:ro projectsyn/commodore:v0.2.0 component new component-name`
  4. `docker run -i --rm --user="$(id -u)" --volume ~/.ssh:/app/.ssh:ro  --volume $PWD/compiled/:/app/compiled/ --volume $PWD/catalog/:/app/catalog/ --volume $PWD/dependencies/:/app/dependencies/ --volume $PWD/inventory/:/app/inventory/ --volume ~/.gitconfig:/app/.gitconfig:ro projectsyn/commodore:v0.2.0 component compile dependencies/component-name`

## Actual Behavior

`Error: Could not find component class file: /app/dependencies/component-name/class/name.yml`

## Expected Behavior

I expect the component to compile normally. This error does not happen if the component name is not `component-name`.

**Comment by simu** [comment] 2020-07-28 11:17
Root cause appears to be that we ignore the `component-` prefix in the directory name, if it exists, cf. https://github.com/projectsyn/commodore/blob/master/commodore/component/compile.py#L26-L27

**Comment by srueg** [comment] 2020-07-28 11:56
Yes exactly. The idea was to support both variants: check-outs of components in directories with and without the `component-` prefix. If a component is manually cloned, it will be in a directory with the prefix. If Commodore clones the repo, it won't have the prefix.

A quick fix would be to forbid the `component-` prefix in component names (in the `component new` command).

**Closed** 2020-07-29 15:13 UTC
Labels: bug
